import Header from "@/components/header";
import Footer from "@/components/footer";
import "./globals.css";
import { Manrope } from "next/font/google";
import { Suspense } from "react";
import Loading from "./feed/loading";
const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata = {
  title: "Netfilm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${manrope.className} bg-black-08 text-white`}>
        <Header />
        <Suspense fallback={<Loading />}>{children}</Suspense>
        <Footer />
      </body>
    </html>
  );
}
